In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('cars_engage_2022.csv')

In [3]:
df.head(10)

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,Tata,Nano Genx,Xma,"Rs. 3,14,815",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,Datsun,Redi-Go,D,"Rs. 2,79,650",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,Datsun,Redi-Go,T,"Rs. 3,51,832",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,Datsun,Redi-Go,A,"Rs. 3,33,419",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Datsun,Redi-Go,S,"Rs. 3,62,000",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail(10)

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
1266,1266,Honda,City,V Mt Petrol,"Rs. 10,65,900",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1267,1267,Honda,City,Vx Mt Petrol,"Rs. 11,82,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1268,1268,Honda,City,Vx Cvt Petrol,"Rs. 13,12,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1269,1269,Honda,City,Sv Mt Diesel,"Rs. 11,11,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1270,1270,Honda,City,V Mt Diesel,"Rs. 11,91,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1271,1271,Honda,City,Vx Mt Diesel,"Rs. 13,02,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1272,1272,Honda,City,Zx Mt Diesel,"Rs. 14,21,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1273,1273,Honda,City,Zx Cvt Petrol,"Rs. 14,31,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1274,1274,Honda,City,V Cvt Petrol,"Rs. 12,01,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1275,1275,Mitsubishi,Montero,3.2 At,"Rs. 68,62,560",3200 cc,4.0,4.0,AWD (All Wheel Drive),In-line,...,Yes,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

In [5]:
df.dtypes

Unnamed: 0             int64
Make                  object
Model                 object
Variant               object
Ex-Showroom_Price     object
                      ...
USB_Ports            float64
Heads-Up_Display      object
Welcome_Lights        object
Battery               object
Electric_Range        object
Length: 141, dtype: object

In [6]:
df.describe()

,Unnamed: 0,Cylinders,Valves_Per_Cylinder,Doors,Seating_Capacity,Number_of_Airbags,USB_Ports
count,1276.000000,1210.000000,1174.000000,1272.000000,1270.000000,1141.000000,29.000000
mean,637.500000,4.380992,3.977853,4.550314,5.270079,3.787029,1.793103
std,368.493781,1.660957,0.833763,0.747816,1.145231,2.522399,0.773642
min,0.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000
25%,318.750000,4.000000,4.000000,4.000000,5.000000,2.000000,1.000000
50%,637.500000,4.000000,4.000000,5.000000,5.000000,2.000000,2.000000
75%,956.250000,4.000000,4.000000,5.000000,5.000000,6.000000,2.000000
max,1275.000000,16.000000,16.000000,5.000000,16.000000,14.000000,3.000000

In [7]:
df.replace("?", np.nan, inplace = True)
df.head(10)

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,Tata,Nano Genx,Xma,"Rs. 3,14,815",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,Datsun,Redi-Go,D,"Rs. 2,79,650",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,Datsun,Redi-Go,T,"Rs. 3,51,832",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,Datsun,Redi-Go,A,"Rs. 3,33,419",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Datsun,Redi-Go,S,"Rs. 3,62,000",799 cc,3.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
missing_data = df.isnull()
missing_data.head(10)

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
5,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
6,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
7,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
8,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
9,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [9]:
# Getting the number of missing values
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

Unnamed: 0
False    1276
Name: Unnamed: 0, dtype: int64

Make
False    1201
True       75
Name: Make, dtype: int64

Model
False    1276
Name: Model, dtype: int64

Variant
False    1276
Name: Variant, dtype: int64

Ex-Showroom_Price
False    1276
Name: Ex-Showroom_Price, dtype: int64

Displacement
False    1264
True       12
Name: Displacement, dtype: int64

Cylinders
False    1210
True       66
Name: Cylinders, dtype: int64

Valves_Per_Cylinder
False    1174
True      102
Name: Valves_Per_Cylinder, dtype: int64

Drivetrain
False    1269
True        7
Name: Drivetrain, dtype: int64

Cylinder_Configuration
False    1263
True       13
Name: Cylinder_Configuration, dtype: int64

Emission_Norm
False    1265
True       11
Name: Emission_Norm, dtype: int64

Engine_Location
False    1233
True       43
Name: Engine_Location, dtype: int64

Fuel_System
False    1268
True        8
Name: Fuel_System, dtype: int64

Fuel_Tank_Capacity
False    1207
True       69
Name: Fuel_Tank_Capacity, dtype: int64

Fuel_Type
False    1276
Name: Fuel_Type, dtype: int64

Height
False    1275
True        1
Name: Height, dtype: int64

Length
False    1276
Name: Length, dtype: int64

Width
False    1264
True       12
Name: Width, dtype: int64

Body_Type
False    1270
True        6
Name: Body_Type, dtype: int64

Doors
False    1272
True        4
Name: Doors, dtype: int64

City_Mileage
False    721
True     555
Name: City_Mileage, dtype: int64

Highway_Mileage
True     800
False    476
Name: Highway_Mileage, dtype: int64

ARAI_Certified_Mileage
False    1162
True      114
Name: ARAI_Certified_Mileage, dtype: int64

ARAI_Certified_Mileage_for_CNG
True     1249
False      27
Name: ARAI_Certified_Mileage_for_CNG, dtype: int64

Kerb_Weight
False    911
True     365
Name: Kerb_Weight, dtype: int64

Gears
False    1171
True      105
Name: Gears, dtype: int64

Ground_Clearance
False    987
True     289
Name: Ground_Clearance, dtype: int64

Front_Brakes
False    1251
True       25
Name: Front_Brakes, dtype: int64

Rear_Brakes
False    1251
True       25
Name: Rear_Brakes, dtype: int64

Front_Suspension
False    1217
True       59
Name: Front_Suspension, dtype: int64

Rear_Suspension
False    1230
True       46
Name: Rear_Suspension, dtype: int64

Front_Track
True     667
False    609
Name: Front_Track, dtype: int64

Rear_Track
True     676
False    600
Name: Rear_Track, dtype: int64

Front_Tyre_&_Rim
False    1227
True       49
Name: Front_Tyre_&_Rim, dtype: int64

Rear_Tyre_&_Rim
False    1228
True       48
Name: Rear_Tyre_&_Rim, dtype: int64

Power_Steering
False    1219
True       57
Name: Power_Steering, dtype: int64

Power_Windows
False    1179
True       97
Name: Power_Windows, dtype: int64

Power_Seats
True     893
False    383
Name: Power_Seats, dtype: int64

Keyless_Entry
False    1002
True      274
Name: Keyless_Entry, dtype: int64

Power
False    1276
Name: Power, dtype: int64

Torque
False    1274
True        2
Name: Torque, dtype: int64

Odometer
False    1233
True       43
Name: Odometer, dtype: int64

Speedometer
False    1231
True       45
Name: Speedometer, dtype: int64

Tachometer
False    1263
True       13
Name: Tachometer, dtype: int64

Tripmeter
False    1216
True       60
Name: Tripmeter, dtype: int64

Seating_Capacity
False    1270
True        6
Name: Seating_Capacity, dtype: int64

Seats_Material
False    1264
True       12
Name: Seats_Material, dtype: int64

Type
False    1275
True        1
Name: Type, dtype: int64

Wheelbase
False    1256
True       20
Name: Wheelbase, dtype: int64

Wheels_Size
False    1220
True       56
Name: Wheels_Size, dtype: int64

Start_/_Stop_Button
True     678
False    598
Name: Start_/_Stop_Button, dtype: int64

12v_Power_Outlet
False    1122
True      154
Name: 12v_Power_Outlet, dtype: int64

Audiosystem
False    1232
True       44
Name: Audiosystem, dtype: int64

Aux-in_Compatibility
False    992
True     284
Name: Aux-in_Compatibility, dtype: int64

Average_Fuel_Consumption
False    931
True     345
Name: Average_Fuel_Consumption, dtype: int64

Basic_Warranty
False    836
True     440
Name: Basic_Warranty, dtype: int64

Bluetooth
False    984
True     292
Name: Bluetooth, dtype: int64

Boot-lid_Opener
False    1262
True       14
Name: Boot-lid_Opener, dtype: int64

Boot_Space
False    1027
True      249
Name: Boot_Space, dtype: int64

CD_/_MP3_/_DVD_Player
False    967
True     309
Name: CD_/_MP3_/_DVD_Player, dtype: int64

Central_Locking
False    1127
True      149
Name: Central_Locking, dtype: int64

Child_Safety_Locks
False    1201
True       75
Name: Child_Safety_Locks, dtype: int64

Clock
False    1142
True      134
Name: Clock, dtype: int64

Cup_Holders
False    1235
True       41
Name: Cup_Holders, dtype: int64

Distance_to_Empty
False    1033
True      243
Name: Distance_to_Empty, dtype: int64

Door_Pockets
False    1159
True      117
Name: Door_Pockets, dtype: int64

Engine_Malfunction_Light
False    1159
True      117
Name: Engine_Malfunction_Light, dtype: int64

Extended_Warranty
True     661
False    615
Name: Extended_Warranty, dtype: int64

FM_Radio
False    1027
True      249
Name: FM_Radio, dtype: int64

Fuel-lid_Opener
False    1262
True       14
Name: Fuel-lid_Opener, dtype: int64

Fuel_Gauge
False    1237
True       39
Name: Fuel_Gauge, dtype: int64

Handbrake
False    1219
True       57
Name: Handbrake, dtype: int64

Instrument_Console
False    1262
True       14
Name: Instrument_Console, dtype: int64

Low_Fuel_Warning
False    1240
True       36
Name: Low_Fuel_Warning, dtype: int64

Minimum_Turning_Radius
False    895
True     381
Name: Minimum_Turning_Radius, dtype: int64

Multifunction_Display
False    1187
True       89
Name: Multifunction_Display, dtype: int64

Sun_Visor
False    1214
True       62
Name: Sun_Visor, dtype: int64

Third_Row_AC_Vents
False    910
True     366
Name: Third_Row_AC_Vents, dtype: int64

Ventilation_System
False    1241
True       35
Name: Ventilation_System, dtype: int64

Auto-Dimming_Rear-View_Mirror
False    656
True     620
Name: Auto-Dimming_Rear-View_Mirror, dtype: int64

Hill_Assist
True     796
False    480
Name: Hill_Assist, dtype: int64

Gear_Indicator
False    777
True     499
Name: Gear_Indicator, dtype: int64

3_Point_Seat-Belt_in_Middle_Rear_Seat
True     1225
False      51
Name: 3_Point_Seat-Belt_in_Middle_Rear_Seat, dtype: int64

Ambient_Lightning
True     1220
False      56
Name: Ambient_Lightning, dtype: int64

Cargo/Boot_Lights
True     1155
False     121
Name: Cargo/Boot_Lights, dtype: int64

Drive_Modes
True     1081
False     195
Name: Drive_Modes, dtype: int64

Engine_Immobilizer
False    1216
True       60
Name: Engine_Immobilizer, dtype: int64

High_Speed_Alert_System
True     1068
False     208
Name: High_Speed_Alert_System, dtype: int64

Lane_Watch_Camera/_Side_Mirror_Camera
True     1210
False      66
Name: Lane_Watch_Camera/_Side_Mirror_Camera, dtype: int64

Passenger_Side_Seat-Belt_Reminder
True     1105
False     171
Name: Passenger_Side_Seat-Belt_Reminder, dtype: int64

Seat_Back_Pockets
False    833
True     443
Name: Seat_Back_Pockets, dtype: int64

Voice_Recognition
True     1144
False     132
Name: Voice_Recognition, dtype: int64

Walk_Away_Auto_Car_Lock
True     1173
False     103
Name: Walk_Away_Auto_Car_Lock, dtype: int64

ABS_(Anti-lock_Braking_System)
False    1144
True      132
Name: ABS_(Anti-lock_Braking_System), dtype: int64

Headlight_Reminder
False    1018
True      258
Name: Headlight_Reminder, dtype: int64

Adjustable_Headrests
False    1026
True      250
Name: Adjustable_Headrests, dtype: int64

Gross_Vehicle_Weight
False    681
True     595
Name: Gross_Vehicle_Weight, dtype: int64

Airbags
False    1144
True      132
Name: Airbags, dtype: int64

Door_Ajar_Warning
False    1133
True      143
Name: Door_Ajar_Warning, dtype: int64

EBD_(Electronic_Brake-force_Distribution)
False    1075
True      201
Name: EBD_(Electronic_Brake-force_Distribution), dtype: int64

Fasten_Seat_Belt_Warning
False    1086
True      190
Name: Fasten_Seat_Belt_Warning, dtype: int64

Gear_Shift_Reminder
False    733
True     543
Name: Gear_Shift_Reminder, dtype: int64

Number_of_Airbags
False    1141
True      135
Name: Number_of_Airbags, dtype: int64

Compression_Ratio
True     917
False    359
Name: Compression_Ratio, dtype: int64

Adjustable_Steering_Column
False    1085
True      191
Name: Adjustable_Steering_Column, dtype: int64

Other_Specs
True     1266
False      10
Name: Other_Specs, dtype: int64

Other_specs
True     1213
False      63
Name: Other_specs, dtype: int64

Parking_Assistance
False    986
True     290
Name: Parking_Assistance, dtype: int64

Key_Off_Reminder
False    936
True     340
Name: Key_Off_Reminder, dtype: int64

USB_Compatibility
False    1009
True      267
Name: USB_Compatibility, dtype: int64

Android_Auto
True     1103
False     173
Name: Android_Auto, dtype: int64

Apple_CarPlay
True     1103
False     173
Name: Apple_CarPlay, dtype: int64

Cigarette_Lighter
True     682
False    594
Name: Cigarette_Lighter, dtype: int64

Infotainment_Screen
False    814
True     462
Name: Infotainment_Screen, dtype: int64

Multifunction_Steering_Wheel
False    925
True     351
Name: Multifunction_Steering_Wheel, dtype: int64

Average_Speed
False    764
True     512
Name: Average_Speed, dtype: int64

EBA_(Electronic_Brake_Assist)
True     690
False    586
Name: EBA_(Electronic_Brake_Assist), dtype: int64

Seat_Height_Adjustment
False    950
True     326
Name: Seat_Height_Adjustment, dtype: int64

Navigation_System
False    683
True     593
Name: Navigation_System, dtype: int64

Second_Row_AC_Vents
False    674
True     602
Name: Second_Row_AC_Vents, dtype: int64

Tyre_Pressure_Monitoring_System
True     936
False    340
Name: Tyre_Pressure_Monitoring_System, dtype: int64

Rear_Center_Armrest
False    717
True     559
Name: Rear_Center_Armrest, dtype: int64

iPod_Compatibility
True     663
False    613
Name: iPod_Compatibility, dtype: int64

ESP_(Electronic_Stability_Program)
True     779
False    497
Name: ESP_(Electronic_Stability_Program), dtype: int64

Cooled_Glove_Box
True     645
False    631
Name: Cooled_Glove_Box, dtype: int64

Recommended_Tyre_Pressure
True     1266
False      10
Name: Recommended_Tyre_Pressure, dtype: int64

Heated_Seats
True     1010
False     266
Name: Heated_Seats, dtype: int64

Turbocharger
False    658
True     618
Name: Turbocharger, dtype: int64

ISOFIX_(Child-Seat_Mount)
True     666
False    610
Name: ISOFIX_(Child-Seat_Mount), dtype: int64

Rain_Sensing_Wipers
True     798
False    478
Name: Rain_Sensing_Wipers, dtype: int64

Paddle_Shifters
True     972
False    304
Name: Paddle_Shifters, dtype: int64

Leather_Wrapped_Steering
True     689
False    587
Name: Leather_Wrapped_Steering, dtype: int64

Automatic_Headlamps
True     774
False    502
Name: Automatic_Headlamps, dtype: int64

Engine_Type
True     1242
False      34
Name: Engine_Type, dtype: int64

ASR_/_Traction_Control
True     834
False    442
Name: ASR_/_Traction_Control, dtype: int64

Cruise_Control
True     727
False    549
Name: Cruise_Control, dtype: int64

USB_Ports
True     1247
False      29
Name: USB_Ports, dtype: int64

Heads-Up_Display
True     1225
False      51
Name: Heads-Up_Display, dtype: int64

Welcome_Lights
True     1207
False      69
Name: Welcome_Lights, dtype: int64

Battery
True     1263
False      13
Name: Battery, dtype: int64

Electric_Range
True     1259
False      17
Name: Electric_Range, dtype: int64